"""autogenerated by genpy from hrl_haptic_manipulation_in_clutter_msgs/ObjectInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ObjectInfo(genpy.Message):
  _md5sum = "c766c32f43d7aa47a71b93fc7d2e259b"
  _type = "hrl_haptic_manipulation_in_clutter_msgs/ObjectInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
float64 obj_id
float64 contact_x
float64 contact_y
float64 contact_z




"""
  __slots__ = ['obj_id','contact_x','contact_y','contact_z']
  _slot_types = ['float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       obj_id,contact_x,contact_y,contact_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.obj_id is None:
        self.obj_id = 0.
      if self.contact_x is None:
        self.contact_x = 0.
      if self.contact_y is None:
        self.contact_y = 0.
      if self.contact_z is None:
        self.contact_z = 0.
    else:
      self.obj_id = 0.
      self.contact_x = 0.
      self.contact_y = 0.
      self.contact_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.obj_id, _x.contact_x, _x.contact_y, _x.contact_z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.obj_id, _x.contact_x, _x.contact_y, _x.contact_z,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.obj_id, _x.contact_x, _x.contact_y, _x.contact_z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.obj_id, _x.contact_x, _x.contact_y, _x.contact_z,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4d = struct.Struct("<4d")
