Header header

string[] joint_names
float64[] joint_angles
float64[] desired_joint_angles
float64[] joint_velocities
float64[] joint_stiffness
float64[] joint_damping

geometry_msgs/Pose torso_pose
geometry_msgs/Pose hand_pose

std_msgs/Float64MultiArray end_effector_jacobian
std_msgs/Float64MultiArray contact_jacobians

hrl_haptic_manipulation_in_clutter_msgs/TaxelArray[] skins


                                                                               
