# Information that is useful for logging and monitoring for each run
# of a controller.

# initial part of the pkl file with the data for this run of the
# controller.
string logging_name

# pose of torso (in world coord frame at the start of the controller)
#geometry_msgs/Pose torso_pose

# local goal that has been commanded for this local controller. (in
# the torso coord frame.)
geometry_msgs/Point local_goal

---

