# Information that is useful for logging and monitoring for each run
# of a controller.

# initial part of the pkl file with the data for this run of the
# controller.
string logging_name

# pose of torso (in world coord frame at the start of the controller)
geometry_msgs/Pose torso_pose

# local goal that has been commanded for this local controller. (in
# the torso coord frame.)
geometry_msgs/Point local_goal

#-----------------------------------------------------------------------
# the names below are the same as the keys in the monitor_param_dict
# that is passed to the local controllers.
#-----------------------------------------------------------------------

# force at which monitoring will stop the controller.
float64 stopping_force
# stop if end effector motion goes below this.
float64 ee_motion_threshold
---

