#!/bin/bash -x

# copy all pngs, pkls generated by pngs_to_pose_pkl.sh into one folder
# per mechanism.

# Usage: ./aggregate.sh <mechanism 1 directory> <directory 2> ...
#

ARGC=$#

if [ $ARGC = 0 ]; then
    echo "Usage: ./aggregate.sh <mechanism 1 directory> <directory 2> ..."
    exit
fi

mkdir aggregated_pkls
#mkdir aggregated_force_pngs
#mkdir aggregated_trajectory_pngs
#mkdir aggregated_poses_dict_pkls

for d in $@
do
    python aggregate_plots.py -d $d -a
    cp $d/mechanism_trajectories_handhook/* aggregated_pkls/
#    cp $d/force_components/* aggregated_force_pngs/
#    cp $d/trajectory_check/* aggregated_trajectory_pngs/
#    cp $d/poses_dict/* aggregated_poses_dict_pkls/
done

echo "All the mechanisms:"
echo $@

#N=1
#while [ $N -leq $ARGC ]
#do
#    echo $N
#    echo ${!N}
#    let N=$N+1
#done




