# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.33
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _videre
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


split_img = _videre.split_img
debayer = _videre.debayer
set_gain = _videre.set_gain
set_exposure = _videre.set_exposure
class VidereCap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VidereCap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VidereCap, name)
    __repr__ = _swig_repr
    __swig_setmethods__["capture"] = _videre.VidereCap_capture_set
    __swig_getmethods__["capture"] = _videre.VidereCap_capture_get
    if _newclass:capture = _swig_property(_videre.VidereCap_capture_get, _videre.VidereCap_capture_set)
    __swig_setmethods__["left"] = _videre.VidereCap_left_set
    __swig_getmethods__["left"] = _videre.VidereCap_left_get
    if _newclass:left = _swig_property(_videre.VidereCap_left_get, _videre.VidereCap_left_set)
    __swig_setmethods__["right"] = _videre.VidereCap_right_set
    __swig_getmethods__["right"] = _videre.VidereCap_right_get
    if _newclass:right = _swig_property(_videre.VidereCap_right_get, _videre.VidereCap_right_set)
    __swig_setmethods__["left_debayered"] = _videre.VidereCap_left_debayered_set
    __swig_getmethods__["left_debayered"] = _videre.VidereCap_left_debayered_get
    if _newclass:left_debayered = _swig_property(_videre.VidereCap_left_debayered_get, _videre.VidereCap_left_debayered_set)
    __swig_setmethods__["right_debayered"] = _videre.VidereCap_right_debayered_set
    __swig_getmethods__["right_debayered"] = _videre.VidereCap_right_debayered_get
    if _newclass:right_debayered = _swig_property(_videre.VidereCap_right_debayered_get, _videre.VidereCap_right_debayered_set)
    def __init__(self, *args): 
        this = _videre.new_VidereCap(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _videre.delete_VidereCap
    __del__ = lambda self : None;
    def process_frames(*args): return _videre.VidereCap_process_frames(*args)
    def set_mode(*args): return _videre.VidereCap_set_mode(*args)
VidereCap_swigregister = _videre.VidereCap_swigregister
VidereCap_swigregister(VidereCap)
cvar = _videre.cvar
NONE = cvar.NONE
RECTIFIED = cvar.RECTIFIED
DISPARITY = cvar.DISPARITY
DISPARITY_RAW = cvar.DISPARITY_RAW



