# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arm_cart_control_gui.ui'
#
# Created: Tue Feb  7 17:26:03 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(702, 476)
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.layoutWidget = QtGui.QWidget(Frame)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 20, 321, 311))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.translate_out = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_out.sizePolicy().hasHeightForWidth())
        self.translate_out.setSizePolicy(sizePolicy)
        self.translate_out.setBaseSize(QtCore.QSize(80, 80))
        self.translate_out.setStyleSheet(_fromUtf8("image: url(:/resources/translate_out.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.translate_out.setText(_fromUtf8(""))
        self.translate_out.setObjectName(_fromUtf8("translate_out"))
        self.gridLayout_2.addWidget(self.translate_out, 0, 0, 1, 1)
        self.translate_up = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_up.sizePolicy().hasHeightForWidth())
        self.translate_up.setSizePolicy(sizePolicy)
        self.translate_up.setBaseSize(QtCore.QSize(80, 80))
        self.translate_up.setStyleSheet(_fromUtf8("image: url(:/resources/translate_up.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.translate_up.setText(_fromUtf8(""))
        self.translate_up.setObjectName(_fromUtf8("translate_up"))
        self.gridLayout_2.addWidget(self.translate_up, 0, 1, 1, 1)
        self.translate_in = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_in.sizePolicy().hasHeightForWidth())
        self.translate_in.setSizePolicy(sizePolicy)
        self.translate_in.setBaseSize(QtCore.QSize(80, 80))
        self.translate_in.setStyleSheet(_fromUtf8("image: url(:/resources/translate_in.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.translate_in.setText(_fromUtf8(""))
        self.translate_in.setObjectName(_fromUtf8("translate_in"))
        self.gridLayout_2.addWidget(self.translate_in, 0, 2, 1, 1)
        self.translate_left = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_left.sizePolicy().hasHeightForWidth())
        self.translate_left.setSizePolicy(sizePolicy)
        self.translate_left.setBaseSize(QtCore.QSize(80, 80))
        self.translate_left.setStyleSheet(_fromUtf8("image: url(:/resources/translate_left.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.translate_left.setText(_fromUtf8(""))
        self.translate_left.setObjectName(_fromUtf8("translate_left"))
        self.gridLayout_2.addWidget(self.translate_left, 1, 0, 1, 1)
        self.translate_right = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_right.sizePolicy().hasHeightForWidth())
        self.translate_right.setSizePolicy(sizePolicy)
        self.translate_right.setBaseSize(QtCore.QSize(80, 80))
        self.translate_right.setStyleSheet(_fromUtf8("image: url(:/resources/translate_right.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.translate_right.setText(_fromUtf8(""))
        self.translate_right.setObjectName(_fromUtf8("translate_right"))
        self.gridLayout_2.addWidget(self.translate_right, 1, 2, 1, 1)
        self.translate_down = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_down.sizePolicy().hasHeightForWidth())
        self.translate_down.setSizePolicy(sizePolicy)
        self.translate_down.setBaseSize(QtCore.QSize(80, 80))
        self.translate_down.setStyleSheet(_fromUtf8("image: url(:/resources/translate_down.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.translate_down.setText(_fromUtf8(""))
        self.translate_down.setObjectName(_fromUtf8("translate_down"))
        self.gridLayout_2.addWidget(self.translate_down, 2, 1, 1, 1)
        self.frame = QtGui.QComboBox(Frame)
        self.frame.setGeometry(QtCore.QRect(420, 350, 261, 31))
        self.frame.setEditable(True)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_2 = QtGui.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(330, 350, 71, 31))
        self.label_2.setStyleSheet(_fromUtf8("font: 16pt;"))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.layoutWidget1 = QtGui.QWidget(Frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 321, 311))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rotate_x_pos = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_x_pos.sizePolicy().hasHeightForWidth())
        self.rotate_x_pos.setSizePolicy(sizePolicy)
        self.rotate_x_pos.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_x_pos.setStyleSheet(_fromUtf8("image: url(:/resources/roate_x_neg.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.rotate_x_pos.setText(_fromUtf8(""))
        self.rotate_x_pos.setObjectName(_fromUtf8("rotate_x_pos"))
        self.gridLayout.addWidget(self.rotate_x_pos, 0, 0, 1, 1)
        self.rotate_y_pos = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_y_pos.sizePolicy().hasHeightForWidth())
        self.rotate_y_pos.setSizePolicy(sizePolicy)
        self.rotate_y_pos.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_y_pos.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_pos.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.rotate_y_pos.setText(_fromUtf8(""))
        self.rotate_y_pos.setObjectName(_fromUtf8("rotate_y_pos"))
        self.gridLayout.addWidget(self.rotate_y_pos, 0, 1, 1, 1)
        self.rotate_x_neg = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_x_neg.sizePolicy().hasHeightForWidth())
        self.rotate_x_neg.setSizePolicy(sizePolicy)
        self.rotate_x_neg.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_x_neg.setStyleSheet(_fromUtf8("image: url(:/resources/roate_x_pos.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.rotate_x_neg.setText(_fromUtf8(""))
        self.rotate_x_neg.setObjectName(_fromUtf8("rotate_x_neg"))
        self.gridLayout.addWidget(self.rotate_x_neg, 0, 2, 1, 1)
        self.rotate_z_neg = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_z_neg.sizePolicy().hasHeightForWidth())
        self.rotate_z_neg.setSizePolicy(sizePolicy)
        self.rotate_z_neg.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_z_neg.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_z_neg.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.rotate_z_neg.setText(_fromUtf8(""))
        self.rotate_z_neg.setObjectName(_fromUtf8("rotate_z_neg"))
        self.gridLayout.addWidget(self.rotate_z_neg, 1, 0, 1, 1)
        self.rotate_z_pos = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_z_pos.sizePolicy().hasHeightForWidth())
        self.rotate_z_pos.setSizePolicy(sizePolicy)
        self.rotate_z_pos.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_z_pos.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_z_pos.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.rotate_z_pos.setText(_fromUtf8(""))
        self.rotate_z_pos.setObjectName(_fromUtf8("rotate_z_pos"))
        self.gridLayout.addWidget(self.rotate_z_pos, 1, 2, 1, 1)
        self.rotate_y_neg = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_y_neg.sizePolicy().hasHeightForWidth())
        self.rotate_y_neg.setSizePolicy(sizePolicy)
        self.rotate_y_neg.setBaseSize(QtCore.QSize(80, 80))
        self.rotate_y_neg.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_neg.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.rotate_y_neg.setText(_fromUtf8(""))
        self.rotate_y_neg.setObjectName(_fromUtf8("rotate_y_neg"))
        self.gridLayout.addWidget(self.rotate_y_neg, 2, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(Frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 350, 271, 111))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setStyleSheet(_fromUtf8("font: 20pt;"))
        self.label.setText(QtGui.QApplication.translate("Frame", "Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.arm_left = QtGui.QPushButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arm_left.sizePolicy().hasHeightForWidth())
        self.arm_left.setSizePolicy(sizePolicy)
        self.arm_left.setBaseSize(QtCore.QSize(80, 80))
        self.arm_left.setStyleSheet(_fromUtf8("image: url(:/resources/arm_left_off.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.arm_left.setText(QtGui.QApplication.translate("Frame", "Left Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.arm_left.setObjectName(_fromUtf8("arm_left"))
        self.horizontalLayout.addWidget(self.arm_left)
        self.arm_right = QtGui.QPushButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arm_right.sizePolicy().hasHeightForWidth())
        self.arm_right.setSizePolicy(sizePolicy)
        self.arm_right.setBaseSize(QtCore.QSize(80, 80))
        self.arm_right.setStyleSheet(_fromUtf8("image: url(:/resources/arm_right_off.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.arm_right.setText(QtGui.QApplication.translate("Frame", "Right Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.arm_right.setObjectName(_fromUtf8("arm_right"))
        self.horizontalLayout.addWidget(self.arm_right)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        pass

import icons_rc
